sudo: required
warnings_are_errors: false
services:
  - docker
before_install:
# Set up environment and create required images
# If no error don't print output
# -  docker-compose run weav > /dev/null
-  docker-compose run weav /bin/sh -c 'pip install . -U && python test/setup_test_env.py'
# -  docker-compose run weav /bin/sh -c 'python test/setup_test_env.py'
script:
# Load packages and install the required packages
# Install retriever from source and run tests
-  docker-compose  run weav /bin/sh -c 'py.test -v -W  ignore::UserWarning' || exit 1
