sudo: required
warnings_are_errors: false
services:
  - docker
before_install:
  - docker-compose ps
# command to run tests using py.test
script:
  - docker-compose  run --service-ports weav py.test -v --cov=retriever