sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
addons:
  postgresql: "9.4"
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install -e
  - pip install codecov -U
  - pip install pytest-cov -U
  - pip install pytest-xdist -U


# command to run test

script:
  - py.test -v --cov=weaver

before_script:
  - sqlite3 --version
  - psql -c 'create database testdb;' -U postgres

after_success:
  - codecov
