version: '3'

services:
  pgdb_weaver:
    image: kartoza/postgis:11.0-2.5
    volumes:
      - ./cli_tools/postgis-data:/var/lib/postgresql
      - ./cli_tools/:/backups
    container_name: pgdb_weav_container
    environment:
      # Lets use sdocker-entrypoint-initdb.d/init-user-db.sh
      # to set up the user and create the user privilege
      # POSTGRES_USER: postgres
      POSTGRES_DB: testdb_weaver
      POSTGRES_PASSWORD: Password12!
      POSTGRES_USER: postgres
    volumes:
      - ./cli_tools/:/tmp/postgis
  weav:
    container_name: weaver_container
    image: weaver_image
    command: bash -c "Python --version"
    environment:
      # If IN_DOCKER is set, use service names as hosts names(travis)
      # otherwise use localhost (local tests)
      "IN_DOCKER" : "true"
      "PGUSER" : "postgres"
      "PGPASSWORD" : "Password12!"
      "PGDATABASE" : "testdb_weaver"
      "PGHOST" : "pgdb_weaver"
    restart: on-failure
    build: .
    
    depends_on:
      - pgdb_weaver
    
    ports:
      - 5001:80
